<header class="messages">
	
	<div class="container">
		<div class="row">
			<div class="col-md-10 col-md-offset-1">
				<nav class="navbar navbar-default">
			    <!-- Brand and toggle get grouped for better mobile display -->
			    <div class="navbar-header">
			      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
			        <span class="sr-only">Toggle navigation</span>
			        <span class="icon-bar"></span>
			        <span class="icon-bar"></span>
			        <span class="icon-bar"></span>
			      </button>
			      <a class="navbar-brand" href="/">
				      <img alt="TLW Solicitors Esign" src="<?php echo SITEROOT; ?>/assets/img/tlw-logo-wide.svg">
				   </a>
			    </div>
			
			    <!-- Collect the nav links, forms, and other content for toggling -->
			    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
			      <ul class="nav navbar-nav navbar-right">
				    <li class="active"><a href="<?php echo SITEROOT; ?>/admin/dashboard/"><i class="fa fa-dashboard"></i> Dashboard</a></li>
			        <li><a href="<?php echo SITEROOT; ?>/admin/settings/"><i class="fa fa-cogs"></i> Settings</a></li>
			        <li><a href="<?php echo SITEROOT; ?>/admin/actions/"><i class="fa fa-bolt"></i> Actions</a></li>
			        <li><a href="<?php echo SITEROOT; ?>"><i class="fa fa-power-off"></i> Log out</a></li>
			      </ul>
				</div><!-- /.navbar-collapse -->
			   
				</nav>
			</div>
		</div>
		<div class="row">
			<div class="col-md-10 col-md-offset-1">
				
				<div class="well well-lg text-center bg-gray no-border">
					<h2>Email success and error logs</h2>
					<p class="lead">The lists below details the inbound emails by date and any IMAP errors when fetching emails.</p>
				</div>
					
			</div>
		</div>
	</div>

</header>
